ACTORS = [
    "le gouvernement",
    "le Premier ministre",
    "le président de la République",
    "le ministre de l'économie",
    "le ministre du travail",
    "le ministre de l'intérieur",
    "le ministre de la justice",
    "le ministre de la santé",
    "le ministre de l'éducation",
    "le ministre de l'industrie",
    "le ministre du budget",
    "un ministre",
    "un secrétaire d'État",
    "le préfet",
    "un préfet de région",
    "le maire",
    "un maire de grande ville",
    "un maire de commune rurale",
    "le conseil municipal",
    "le conseil régional",
    "le conseil général",
    "l'administration centrale",
    "les services de l'État",
    "une administration locale",
    "le Parlement",
    "l'Assemblée nationale",
    "le Sénat",
    "une commission parlementaire",
    "un rapporteur",
    "un haut fonctionnaire"
]

SITUATIONS = [
    "une déclaration publique",
    "une intervention télévisée",
    "une session parlementaire",
    "une séance à l'Assemblée nationale",
    "une séance au Sénat",
    "une conférence de presse",
    "une allocution officielle",
    "une réunion interministérielle",
    "un conseil des ministres",
    "une visite officielle",
    "un déplacement en région",
    "une inauguration",
    "une réunion de crise",
    "un débat parlementaire",
    "une audition parlementaire",
    "une interview radiophonique",
    "une intervention médiatique",
    "une présentation budgétaire",
    "une discussion de loi",
    "une commission d'enquête",
    "une réunion administrative",
    "une rencontre avec des élus",
    "une réunion avec des partenaires sociaux",
    "une table ronde",
    "un sommet européen",
    "une négociation européenne",
    "une déclaration internationale",
    "une réunion diplomatique"
]

TOPICS = [
    "le chômage de masse",
    "la montée du chômage des jeunes",
    "les contrats précaires",
    "le développement du temps partiel",
    "la désindustrialisation",
    "la fermeture de sites industriels",
    "les délocalisations",
    "la compétitivité industrielle",
    "la modernisation industrielle",
    "les privatisations d'entreprises publiques",
    "les nationalisations",
    "la restructuration du secteur public",
    "la réforme de l'État",
    "la modernisation administrative",
    "le déficit public",
    "la dette de l'État",
    "la maîtrise des dépenses publiques",
    "la fiscalité des ménages",
    "la pression fiscale",
    "la création de la CSG",
    "le financement de la sécurité sociale",
    "l'assurance maladie",
    "le système de retraites",
    "la réforme des retraites",
    "le pouvoir d'achat",
    "l'inflation",
    "le logement social",
    "la crise du logement",
    "la politique de la ville",
    "les banlieues",
    "les violences urbaines",
    "la délinquance",
    "la sécurité intérieure",
    "le maintien de l'ordre",
    "la police nationale",
    "la justice pénale",
    "la réforme judiciaire",
    "les prisons",
    "l'immigration",
    "le contrôle des frontières",
    "le droit d'asile",
    "l'intégration",
    "les tensions identitaires",
    "les discriminations",
    "le racisme",
    "la montée du Front national",
    "la crise politique",
    "l'abstention électorale",
    "la cohabitation",
    "le rôle du président",
    "le rôle du gouvernement",
    "la Ve République",
    "la construction européenne",
    "le traité de Maastricht",
    "l'intégration européenne",
    "la souveraineté nationale",
    "la convergence économique",
    "la monnaie européenne",
    "les accords de Schengen",
    "la libre circulation",
    "l'éducation publique",
    "la réforme scolaire",
    "les universités",
    "l'échec scolaire",
    "les hôpitaux publics",
    "le système de santé",
    "les dépenses de santé",
    "l'énergie nucléaire",
    "EDF et GDF",
    "les transports publics",
    "la SNCF",
    "les télécommunications",
    "la poste",
    "l'aménagement du territoire"
]